version: "3.7"

services:
    pi_video_matrix:
        image: jacktester/pi_video_matrix
        container_name: pi_video_matrix
        devices:
            - /dev/vchiq:/dev/vchiq
            - /dev/fb0:/dev/fb0
            - /dev/tty2:/dev/tty2
        volumes:
            - ./conf:/etc/pi_video_matrix/
            - /opt/vc:/opt/vc
        cap_add:
            - SYS_TTY_CONFIG

# docker-compose run --rm pi_video_matrix

# /dev/vchiq /opt/vc required for omxplayer
# /dev/fb0 /dev/tty2 SYS_TTY_CONFIG required for fbi blanking