#!/bin/sh

# See /etc/displaycameras/schedule.conf for configuration options

conf=/etc/displaycameras

if [ -r /etc/displaycameras/schedule.conf ]
then
	. $conf/schedule.conf;
else
	echo "$conf/schedule.conf does not exist or is not readable."
exit 1
fi

while :
do
	dow=$(date +%w)
	if [ "$dow" -eq 0 ]
	then
		# Sunday
		if [ "$sun_on" ="" ] || [ "$sun_off" == "" ]
		then
			# Off
			sleep 3600
		fi
	elif [ "$dow" -eq 6 ]
	then
		# Saturday
		if [ "$sat_on" ="" ] || [ "$sat_off" == "" ]
		then
			# Off
			sleep 3600
		elif [ "$(date +%H%M)" -ge "$sat_on" ] && [ "$(date +%H%M)" -le "$sat_off" ]
		# Open
		then
			vcgencmd display_power 1
			if [ ! -f "/var/run/displaycameras.pid" ]
			then
				displaycameras start
			fi
			while [ "$(date +%H%M)" -ge "$sat_on" ] && [ "$(date +%H%M)" -le "$sat_off" ]
			do
				displaycameras repair
				sleep 60
			done
		elif [ "$(date +%H%M)" -le "$sat_on" ] || [ "$(date +%H%M)" -ge "$sat_off" ]
		# Closed
		then
			if [ -f "/var/run/displaycameras.pid" ]
			then
				displaycameras stop
			fi
			vcgencmd display_power 0
			while [ "$(date +%H%M)" -le "$sat_on" ] || [ "$(date +%H%M)" -ge "$sat_off" ]
			do
				sleep 60
			done
		fi
	else
		# Weekday
		if [ "$weekday_on" ="" ] || [ "$weekday_off" == "" ]
		then
			# Off
			sleep 3600
		elif [ "$(date +%H%M)" -ge "$weekday_on" ] && [ "$(date +%H%M)" -le "$weekday_off" ]
		# Open
		then
			vcgencmd display_power 1
			if [ ! -f "/var/run/displaycameras.pid" ]
			then
				displaycameras start
			fi
			while [ "$(date +%H%M)" -ge "$weekday_on" ] && [ "$(date +%H%M)" -le "$weekday_off" ]
			do
				displaycameras repair
				sleep 60
			done
		elif [ "$(date +%H%M)" -le "$weekday_on" ] || [ "$(date +%H%M)" -ge "$weekday_off" ]
		# Closed
		then
			if [ -f "/var/run/displaycameras.pid" ]
			then
				displaycameras stop
			fi
			vcgencmd display_power 0
			while [ "$(date +%H%M)" -le "$weekday_on" ] || [ "$(date +%H%M)" -ge "$weekday_off" ]
			do
				sleep 60
			done
		fi
	fi
done
